baseURL = "https://david-hollingworth.github.io/nailed-it-blog/"
languageCode = "en-gb"
title = "Nailed-It: The Blog"
theme = "nailed-it-blog"

disablePathToLower = true

[permalinks]
  posts = "/posts/:slug/"

[taxonomies]
  tag = "tags"

[params]
  description = "Nailed-It news, views and releases"
  dateFormat = "2 January 2006"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  style = "monochrome"
